
backend = "glx";
vsync =false;

# Enable transparency
inactive-opacity = 0.96;
active-opacity = 1.0;
frame-opacity=1

opacity-rule = [
  "85:class_g = 'i3bar'"
];

# Blur 
# blur-background=true;
# blur-background-exclude = [
# "window_type = 'dock'" ,
# ];
blur-background-exclude = [];
blur-method= "dual_kawase";
# blur-strength= 5;
blur-strength= 0;


# Avoid tearing
use-damage = true;

# Fix for some GTK apps
unredir-if-possible = false;

wintypes:
{
  dock = {
    opacity = 0.82;
    blur-background = true;
    blur-strength = 8;
  };
};

# --- Rounded corners ---
corner-radius = 0;

rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "class_g = 'i3bar'",
  "class_g = 'Polybar'",
  "class_g = 'i3blocks'"
];

