#!/usr/bin/env bash

PROFILE=$(tuned-adm active 2>/dev/null | awk '{print $4}')

case "$PROFILE" in
  throughput-performance)
    ICON=" 󰓅 "   # performance
    ;;
  balanced)
    ICON=" 󰈐 "   # balanced
    ;;
  balanced-battery)
    ICON=" 󰂃 "   # battery saver
    ;;
  powersave)
    ICON=" 󰂃 "
    ;;
  *)
    ICON=" 󰞋 "
    ;;
esac

# Full text
echo "$ICON"

# Short text
echo "$ICON"

# Color
echo "$COLOR"
