#!/usr/bin/env bash

# Get volume and mute status
VOL=$(pamixer --get-volume)
MUTE=$(pamixer --get-mute)

if [ "$MUTE" = "true" ]; then
    echo " "
    echo " "
else
    echo " ${VOL}%"
    echo " ${VOL}%"

fi
